CREATE TABLE patients
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name VARCHAR(255)                            NOT NULL,
    last_name  VARCHAR(255)                            NOT NULL,
    passport   VARCHAR(255)                            NOT NULL,
    phone      VARCHAR(255),
    birth_date date                                    NOT NULL,
    email      VARCHAR(255)                            NOT NULL,
    deleted    BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_patients PRIMARY KEY (id)
);

CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(255)                            NOT NULL,
    password VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE patients
    ADD CONSTRAINT uc_patients_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);